# Generated by Django 3.0.7 on 2020-07-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=120, null=True)),
                ('Exercises', models.CharField(max_length=120, null=True)),
                ('Muscles_Involved', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
